name: Build and upload to release

on:
  push:
    branch:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Maven cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
    - name: Build with Maven
      run: mvn package --file plugin/pom.xml -DskipTests
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S %Z')"
    - name: Create tag name from date
      id: tagdate
      run: echo "::set-output name=tagdate::$(date +'%Y-%m-%d_%H-%M-%S_%Z')"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tagdate.outputs.tagdate }}
        release_name: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
    - name: Upload main asset
      id: upload-main-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: plugin/module-main/target/plugin_intranda_administration_ruleset_compatibility.jar
        asset_name: plugin_intranda_administration_ruleset_compatibility.jar
        asset_content_type: application/jar
    - name: Upload GUI asset
      id: upload-gui-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: plugin/module-gui/target/plugin_intranda_administration_ruleset_compatibility-GUI.jar
        asset_name: plugin_intranda_administration_ruleset_compatibility-GUI.jar
        asset_content_type: application/jar
    - name: Upload Config asset
      id: upload-config-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: plugin/plugin_intranda_administration_ruleset_compatibility.xml
        asset_name: plugin_intranda_administration_ruleset_compatibility.xml
        asset_content_type: text/xml